version: '3.8'
services:
    php:
      build: .
      container_name: mailer-dev
      ports:
        - "8000:8000"
      volumes:
          - .:/var/www
      command: ["php","artisan","serve","--host=0.0.0.0"]

    database:
        container_name: mailer-database-dev
        image: mysql:latest
        restart: always
        environment:
          MYSQL_DATABASE: ${DB_DATABASE}
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
          - "3306:3306"
