version: '3.8'
services:
    database:
        container_name: mailer-database-dev
        image: mysql:latest
        restart: always
        environment:
          MYSQL_DATABASE: ${DB_DATABASE}
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
          - "3306:3306"
